version: 2.1
jobs: 
  build:
    docker:
      - image: cimg/node:14.10.1
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ cheksum 'package.json' }}

      - run:
          command: npm install

      - save_cach:
          key: v1-dependencies-{{ cheksum 'package.json' }}
          paths:
            - node_modules
      - run:
          command: npm test